# Generated by Django 5.1.6 on 2025-03-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('MANUFACTURED', 'Manufactured'), ('SHIPPED', 'Shipped'), ('RECEIVED_AT_WAREHOUSE', 'Received at Warehouse'), ('DELIVERED', 'Delivered to Store'), ('SHELVED', 'Shelved for Sale')], max_length=50),
        ),
    ]
