# Generated by Django 5.1.6 on 2025-03-02 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_alter_transaction_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='recall_reason',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_recalled',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recall_date',
        ),
        migrations.AddField(
            model_name='product',
            name='current_stage',
            field=models.CharField(default='MANUFACTURED', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
